plugins:
  - path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/feat/yarn3/dist/yarn-plugin-nixify.js"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
